// <auto-generated>
// Generated by RegistryEnumGenerator
// </auto-generated>
using System;

namespace GeneratedEnums
{
    [Flags]
    public enum ActionId : int
    {
        None = 0,
        Apply = 1 << 0,
        Decreased = 1 << 1,
        Increase = 1 << 2,
        Remove = 1 << 3,
    }

    [Flags]
    public enum AttitudeId : int
    {
        None = 0,
        Ally = 1 << 0,
        Any = 1 << 1,
        Enemy = 1 << 2,
        Me = 1 << 3,
        Random = 1 << 4,
    }

    [Flags]
    public enum DirectionId : int
    {
        None = 0,
        ALL = 1 << 0,
        Back = 1 << 1,
        BackLeft = 1 << 2,
        BackRight = 1 << 3,
        Front = 1 << 4,
        FrontLeft = 1 << 5,
        FrontRight = 1 << 6,
        Left = 1 << 7,
        Right = 1 << 8,
    }

    [Flags]
    public enum EffectId : int
    {
        None = 0,
        Any = 1 << 0,
        Burn = 1 << 1,
        Charge = 1 << 2,
        Damage = 1 << 3,
        Freeze = 1 << 4,
        Haste = 1 << 5,
        Heal = 1 << 6,
        Random = 1 << 7,
        Slow = 1 << 8,
    }

    [Flags]
    public enum ModifierId : int
    {
        None = 0,
        ForFight = 1 << 0,
        Forever = 1 << 1,
        Least = 1 << 2,
        Most = 1 << 3,
    }

    [Flags]
    public enum OperatinoId : int
    {
        None = 0,
        ApplyEffect = 1 << 0,
        Buy = 1 << 1,
        Died = 1 << 2,
        Improve = 1 << 3,
        ReceiveEffect = 1 << 4,
        Ressurected = 1 << 5,
        Sell = 1 << 6,
        Transform = 1 << 7,
    }

    [Flags]
    public enum StatsId : int
    {
        None = 0,
        BlockChance = 1 << 0,
        Cooldown = 1 << 1,
        CriticalChance = 1 << 2,
        CriticalDamage = 1 << 3,
        CurrentHealth = 1 << 4,
        Damage = 1 << 5,
        DodgeChance = 1 << 6,
        MaxHealth = 1 << 7,
        Regeneration = 1 << 8,
    }

    [Flags]
    public enum TagId : int
    {
        None = 0,
        Clothes = 1 << 0,
        Elf = 1 << 1,
        Food = 1 << 2,
        Friend = 1 << 3,
        Goblin = 1 << 4,
        Human = 1 << 5,
        Orc = 1 << 6,
        Tool = 1 << 7,
        Undead = 1 << 8,
        Weapon = 1 << 9,
    }

}
