// <auto-generated>
// Generated by RegistryEnumGenerator
// </auto-generated>
using System;

namespace GeneratedEnums
{
    [Flags]
    public enum ActionId : int
    {
        None = 0,
        Apply = 1 << 0,
        Decreased = 1 << 1,
        Increase = 1 << 2,
        Remove = 1 << 3,
    }

    [Flags]
    public enum AttitudeId : int
    {
        None = 0,
        Ally = 1 << 0,
        Enemy = 1 << 1,
        Me = 1 << 2,
        Random = 1 << 3,
    }

    [Flags]
    public enum CreatureBehaviorProfileId : int
    {
        None = 0,
        _1x1 = 1 << 0,
        _2x2 = 1 << 1,
        Стайный_гоблин = 1 << 2,
    }

    [Flags]
    public enum DirectionId : int
    {
        None = 0,
        ALL = 1 << 0,
        Back = 1 << 1,
        BackLeft = 1 << 2,
        BackRight = 1 << 3,
        Front = 1 << 4,
        FrontLeft = 1 << 5,
        FrontRight = 1 << 6,
        Left = 1 << 7,
        Right = 1 << 8,
    }

    [Flags]
    public enum EffectId : int
    {
        None = 0,
        Damage = 1 << 0,
        Heal = 1 << 1,
    }

    [Flags]
    public enum ModifierId : int
    {
        None = 0,
        ForFight = 1 << 0,
        Forever = 1 << 1,
        Least = 1 << 2,
        Most = 1 << 3,
    }

    [Flags]
    public enum RaceId : int
    {
        None = 0,
        Elf = 1 << 0,
        Goblin = 1 << 1,
        Human = 1 << 2,
        Orc = 1 << 3,
        Undead = 1 << 4,
    }

    [Flags]
    public enum StatsId : int
    {
        None = 0,
        Cooldown = 1 << 0,
        CritChance = 1 << 1,
        CritDmg = 1 << 2,
        CurrentHealth = 1 << 3,
        Damage = 1 << 4,
        MaxHealth = 1 << 5,
    }

}
